SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIOPROGRAMACAO;

CREATE DATABASE DBEXERCICIOPROGRAMACAO;
USE DBEXERCICIOPROGRAMACAO;

CREATE TABLE CADASTRO(
  IDCADASTRO INT NOT NULL AUTO_INCREMENT
  ,NOME VARCHAR(120) NOT NULL
  ,DOC_IDENTIFICACAO CHAR(11)
  ,SENHA CHAR(12)
  ,EMAIL VARCHAR(120)
  ,PRIMARY KEY(IDCADASTRO)
);
CREATE TABLE USUARIO_GOVERNO(
   IDUSUARIO_GOVERNO INT NOT NULL AUTO_INCREMENT
  ,DOC_IDENTIFICACAO CHAR(11) NOT NULL
  ,SENHA CHAR(20)
  ,IDCADASTRO INT
  ,DT_NASCIMENTO DATE
  ,PRIMARY KEY (IDUSUARIO_GOVERNO)
  ,FOREIGN KEY(IDCADASTRO) REFERENCES CADASTRO(IDCADASTRO)
);
CREATE TABLE USUARIO_IMIGRANTE(
   IDUSUARIO_IMIGRANTE INT NOT NULL AUTO_INCREMENT
  ,NOME VARCHAR(120) NOT NULL
  ,DT_NASCIMENTO DATE
  ,EMAIL VARCHAR(120)
  ,NACIONALIDADE VARCHAR(50)
  ,ESCOLARIDADE VARCHAR(120)
  ,PAIS_FORMACAO VARCHAR(120)
  ,CURSO VARCHAR (120)
  ,PROFISSAO VARCHAR(120)
  ,EMPREGADO CHAR(3)
  ,IDCADASTRO INT
  ,PRIMARY KEY(IDUSUARIO_IMIGRANTE)
  ,FOREIGN KEY(IDCADASTRO) REFERENCES CADASTRO(IDCADASTRO)
);
CREATE TABLE CONSULTA_EMPREGO(
  IDCONSULTA_EMPREGO INT NOT NULL AUTO_INCREMENT
  ,EMPRESA VARCHAR (120) NOT NULL
  ,REQUISITO VARCHAR(120)
  ,ENDERECO VARCHAR(120)
  ,VAGA VARCHAR (120)
  ,DT_PUBLICACAO DATE
  ,IDUSUARIO_IMIGRANTE INT
  ,PRIMARY KEY(IDCONSULTA_EMPREGO)
  ,FOREIGN KEY(IDUSUARIO_IMIGRANTE) REFERENCES USUARIO_IMIGRANTE(IDUSUARIO_IMIGRANTE)
);
